### ISSUE TITLE
inconsistent state

### ISSUE THREAD

**Issue by ArneBinder** [santhoshtr/wikipedia-ipfs#3]
# Problem
Currently, all internal links (to other wikipedia articles) implicitly point to newest revisions. That is to say, a revision is kind of **mutible**.

# Expected Behaviour
The internal links in one article should point to revisions that were latest at the time when the article itself was edited i.e. when its revision was created.

# Possible Solution?
Add the `oldid` argument with the respective id to the link targets for all relative links. This may give you sth more close to a real snapshot. Using revision cids would be even better, but I have no clue how to do that easily.

Nevertheless, thanks for this very cool progressive web app!

**Comment by santhoshtr** [comment]
This problem is addressed in my latest architecture outline. Each article is a linked data in a big IPLD structure identified by a CID. A CID is a snapshot of time. If we get an article "A" and it points to "B", the reader application(the way a user use this IPLD) resolves B from same IPLD with same CID. 

See [README.md](../) for more information

**Comment by ArneBinder** [comment]
The new architecture looks very nice.
